#
server:
  port: 7200
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-zuul

#注册中心配置
eureka:
  instance:
    hostname: 114.67.102.8
    prefer-ip-address: true
  client:
    defaultZone: http://114.67.102.8:7100/eureka/
#路由转发超时配置
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
#服务转发配置
zuul:
  add-host-header: true
  routes:
    study-springcloud-provider:
      path: /**
      serviceId:
      sensitiveHeaders: "*"
