###
server:
  address: 127.0.0.1
  port: 7000
###
logging:
  config: classpath:logback.xml
###
spring:
  application:
    name: springcloud-eureka
###
eureka:
  instance:
    hostname: 127.0.0.1
    #服务刷新时间配置，每隔这个时间会主动心跳一次，默认30s
    lease-renewal-interval-in-seconds: 5
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
  server:
    #自我保护关机制
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
###
zuul:
  add-host-header: true
  routes:
    study-springcloud-provider:
      path

