#
server:
  port: 7020
  tomcat:
    max-threads: 300
    max-connections: 1000
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-zuul
  servlet:
    multipart:
      enabled: true
      max-file-size: 100Mb
      max-request-size: 100Mb
##############################
#（★）Eureka
##############################
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#  client:
#    fetch-registry: true
#    service-url:
#      defaultZone: http://114.67.102.8:7010/eureka/
##############################
#（★）Ribbon
##############################
ribbon:
  #设置路由转发请求时，创建请求连接的超时时间
  ConnectTimeout: 6000
  #转发超时
  ReadTimeout: 6000
  #是否对所有操作重试
  OkToRetryOnAllOperations: true
  #同一实例的重试次数
  MaxAutoRetries: 1
  #同一服务不同实例的重试次数
  MaxAutoRetriesNextServer: 2
##############################
#（★）Hystrix
##############################
hystrix:
  command:
    default:
      #（▲）执行
      execution:
        #隔离策略，默认是Thread, 可选Thread｜Semaphore
        isolation:
          strategy: Thread
          thread:
            timeoutInMillisecond: 6000 #命令执行超时时间，默认1000ms
          semaphore:
            maxConcurrentRequests:
      #（▲）熔断
      circuitBreaker:
        forceOpen: false
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 100
        errorThresholdPercentage: 50
      #（▲）回退，降级
      fallback:
        enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 50
##############################
#（★）Route
##############################
zuul:
  #（▲）隔离策略
  ribbon-isolation-strategy: semaphore
  semaphore:
    max-semaphores: 100
  #（▲）主机配置
  host:
    max-total-connections: 200
    max-per-route-connections: 20
    m
  #（▲）解饿加载
  ribbon:
    eager-load: true
  #（▲）路由前缀
  prefix: /api
  #（▲）忽略表达式
  ignored-services: aa
  ignored-headers: Cookie
  ignored-patterns: /**/hello/**
  #（▲）全局过滤
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  #（▲）全局重试
  retryable: true
  #（▲）路由
  routes:
    study-springcloud-provider:
      path: /**
      service-id: study-springcloud-provider
      #路由过滤
      sensitive-headers: "*"
      #路由重试
      retryable: true
####################
#（★）OAuth2
####################
security:
  #  basic:
  #    enabled: false
  oauth2:
    client:
      access-token-uri: http://114.67.102.8:7010
      user-authorization-uri: http://114.67.102.8:7010
      client-id: client_1
      client-secret: secret_1
    resource:
      jwt:
        key-value: spring123