###
server:
  port: 7000
###
logging:
  config: classpath:logback.xml
###
spring:
  application:
    name: springcloud-zuul
###
eureka:
  instance:
    hostname: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  server:
    enable-self-preservation: false
  client:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
###
zuul:
  add-host-header: true
  routes:
    study-springcloud-provider:
      path: /**
      serviceId: sdffsf
      sensitiveHeaders: "*"

