server:
  port: @server.port@
#
logging:
  config: classpath:logback.xml
#
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    service-url:
      defaultZone: @eureka.server.list@
#
spring:
  application:
    name: study-springcloud-zuul
  main:
    web-application-type: servlet
    banner-mode: console
  profiles:
#    active: zuul
    active: zuul,ribbon
#    active: zuul,ribbon,hystrix
