#
server:
  port: 7200
  tomcat:
    max-threads: 300
    max-connections: 1000
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-zuul
  servlet:
    multipart:
      enabled: true
      max-file-size: 100
      max-request-size: 100
##############################
#（★）Eureka
##############################
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    service-url:
      defaultZone: @eureka.client.defaultZone@
##############################
#（★）Ribbon
##############################
ribbon:
  #设置路由转发请求时，创建请求连接的超时时间
  ConnectTimeout: 6000
  #转发超时
  ReadTimeout: 6000
  #是否对所有操作重试
  OkToRetryOnAllOperations: true
  #同一实例的重试次数
  MaxAutoRetries: 1
  #同一服务不同实例的重试次数
  MaxAutoRetriesNextServer: 2
##############################
#（★）Hystrix
##############################
hystrix:
  command:
    default:
      #（▲）执行
      execution:
        timeout:
          #执行是否启用超时，默认启用true
          enabled: true
        #隔离策略，默认是Thread, 可选Thread｜Semaphore
        isolation:
          strategy: Thread
          thread:
            #命令执行超时时间，默认1000ms
            timeoutInMillisecond: 6000
            #发生超时是是否中断，默认true
            interruptOnTimeout: true
          semaphore:
            maxConcurrentRequests: 100
      #（▲）熔断
      circuitBreaker:
        #用来跟踪circuit的健康性，如果未达标则让请求短路。默认true
        enabled: true
        #强制打开熔断器，如果打开这个开关，那么拒绝所有请求，默认false
        forceOpen: false
        #强制关闭熔断器 如果这个开关打开，circuit将一直关闭且忽略
        closedOpen: true
        #错误比率阀值，如果错误率>=该值，circuit会被打开，并短路所有请求触发fallback。默认50
        errorThresholdPercentage: 50
        #触发短路的时间值，当该值设为5000时，则当触发circuit break后的5000毫秒内都会拒绝request，也就是5000毫秒后才会关闭circuit
        sleepWindowInMilliseconds: 100
        #
        requestVolumeThreshold: 20
      #（▲）回退，降级
      fallback:
        enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 50
##############################
#（★）Route
##############################
zuul:
  #（▲）隔离策略
  ribbon-isolation-strategy: semaphore
  semaphore:
    max-semaphores: 100
  #（▲）主机配置
  host:
    max-total-connections: 200
    max-per-route-connections: 20
  #（▲）解饿加载
  ribbon:
    eager-load: true
  #（▲）路由前缀
  prefix: /api
  #（▲）忽略表达式
  ignored-services: aa
  ignored-headers: Cookie
  ignored-patterns: /**/hello/**
  #（▲）全局过滤
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  #（▲）全局重试
  retryable: true
  ####################
  #（▲）路由
  ####################
  routes:
    study-springcloud-provider:
      path: /**
      service-id: study-springcloud-provider
      #路由过滤
      sensitive-headers: "*"
      #路由重试
      retryable: true
####################
#（★）OAuth2
####################
security:
  #  basic:
  #    enabled: false
  oauth2:
    client:
      access-token-uri: http://114.67.102.8:7010
      user-authorization-uri: http://114.67.102.8:7010
      client-id: client_1
      client-secret: secret_1
    resource:
      jwt:
        key-value: spring123