#
server:
  port: 7200
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-zuul

#注册中心配置
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://114.67.102.8:7100/eureka/
#服务转发配置
zuul:
  add-host-header: true
  routes:
    study-springcloud-provider:
      path: /**
      service-id: study-springcloud-provider
      sensitive-headers: "*"