#==============================
#（★）Ribbon
#==============================
ribbon:
  #（▲）Eureka配置
  eureka:
    enabled: true
  #（▲）连接和读取超时时间
  ConnectTimeout: 5000
  ReadTimeout: 5000
  #（▲）重试
  #所有操作都支持重试的开关
  OkToRetryOnAllOperations: true
  #出错或超时，Server重试的次数（除去首次）
  MaxAutoRetries: 1
  #在其他Server上重试的次数（除去首次）
  MaxAutoRetriesNextServer: 1
#study-springcloud-client-rest:
#  ribbon:
#    ConnectTimeout: 3000
#    ReadTimeout: 3000
#    OkToRetryOnAllOperations: true
#    MaxAutoRetries: 0
#    MaxAutoRetriesNextServer: 0
