#
server:
  port: 7200
#
logging:
  config: classpath:logback-spring.xml
#
spring:
  application:
    name: study-springcloud-zuul
  main:
    web-application-type: servlet
    banner-mode: off
  profiles:
    active: zuul
#    active: zuul,ribbon
#    active: zuul,ribbon,hystrix
#
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    service-url:
      defaultZone: @eureka.server.list@