#
server:
  port: 7001
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: springcloud-zuul

# 注册中心配置
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 路由转发超时配置
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000

# 服务转发配置
zuul:
  add-host-header: true
  routes:
    study-springcloud-provider:
      path: /**
      serviceId: sdffsf
      sensitiveHeaders: "*"

