version: '3.6'
services:
  zuul-server1:
    image: study/study-springcloud-zuul:1
    ports:
      - "7201:7201"
    environment:
      - SERVER_PORT=7201
      - EUREKA_SERVER_LIST=http://eureka-server1:7101/eureka/,http://eureka-server2:7102/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - overlay_net
  zuul-server2:
    image: study/study-springcloud-zuul:1
    ports:
      - "7202:7202"
    environment:
      - SERVER_PORT=72002
      - EUREKA_SERVER_LIST=http://eureka-server1:7101/eureka/,http://eureka-server2:7102/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - overlay_net

networks:
  overlay_net:
    external: true
