version: '3.6'
services:
  zuul-server:
    image: study/study-springcloud-zuul:1
    hostname: eureka-server1
    ports:
      - "7200:7200"
    environment:
      - SERVER_PORT=7200
      - EUREKA_SERVER_LIST=http://eureka-server2:7102/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - overlay_net

networks:
  overlay_net:
    external: true
